package com.oreilly.springaicourse;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.ai.audio.tts.TextToSpeechPrompt;
import org.springframework.ai.audio.tts.TextToSpeechResponse;
import org.springframework.ai.elevenlabs.ElevenLabsTextToSpeechModel;
import org.springframework.ai.elevenlabs.ElevenLabsTextToSpeechOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * ElevenLabs text-to-speech demo (Lab 9 extension).
 *
 * Uses the same Spring AI TextToSpeechPrompt/TextToSpeechResponse abstraction
 * as the OpenAI TTS lab -- only the injected model changes.
 *
 * Voice IDs are scoped to an ElevenLabs account: a cloned voice only works
 * with the API key of the account that owns it. Set ELEVENLABS_VOICE_ID to a
 * voice from your own account; without it, the public "Rachel" voice is used.
 */
@SpringBootTest
@EnabledIfEnvironmentVariable(named = "ELEVENLABS_API_KEY", matches = ".+")
class ElevenLabsTests {

    @Test
    void textToSpeechWithConfiguredVoice(@Autowired ElevenLabsTextToSpeechModel ttsModel) {
        String text = """
                Welcome to Spring AI. This audio was generated by ElevenLabs
                using the voice configured for this account.""";

        // Voice and model come from spring.ai.elevenlabs.tts.* properties
        TextToSpeechPrompt prompt = new TextToSpeechPrompt(text);
        TextToSpeechResponse response = ttsModel.call(prompt);
        assertNotNull(response);

        saveAudio(response.getResult().getOutput(), "elevenlabs_configured_voice.mp3");
    }

    @Test
    void textToSpeechWithPerCallOptions(@Autowired ElevenLabsTextToSpeechModel ttsModel) {
        // Options can also be supplied per call, overriding the properties
        var options = ElevenLabsTextToSpeechOptions.builder()
                .voiceId(System.getenv().getOrDefault(
                        "ELEVENLABS_VOICE_ID", "21m00Tcm4TlvDq8ikWAM"))
                .modelId("eleven_multilingual_v2")
                .build();

        TextToSpeechPrompt prompt = new TextToSpeechPrompt(
                "Per-call options override the application properties.", options);
        TextToSpeechResponse response = ttsModel.call(prompt);
        assertNotNull(response);

        saveAudio(response.getResult().getOutput(), "elevenlabs_per_call_options.mp3");
    }

    private void saveAudio(byte[] audio, String fileName) {
        try {
            Path outputPath = Path.of("build", "generated-audio", fileName);
            Files.createDirectories(outputPath.getParent());
            Files.write(outputPath, audio);
            System.out.println("Audio saved as " + outputPath);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
